replicaCount: 1

image:
  repository: 192.168.49.2:30002/library/python-app
  tag: "1.0.202608121113-150438e"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
