apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: java-ci-run-
spec:
  pipelineRef:
    name: java-ci-pipeline
  params:
    - name: repo-url
      value: "https://github.com/nishank12-nk/dc-dr-gitops-deployment.git"
    - name: revision
      value: "main"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
    - name: git-credentials
      secret:
        secretName: git-credentials
    - name: docker-credentials
      secret:
        secretName: harbor-docker-credentials
        items:
          - key: .dockerconfigjson
            path: config.json
